name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Java projects and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test project-a
        run: mvn -f morse-code/pom.xml clean verify

      - name: Build and test project-b
        run: mvn -f movie-rental.refactor/pom.xml clean verify

      - name: Build and test project-c
        run: mvn -f streams-kata/pom.xml clean verify